import { useCallback } from 'react';
import { parseMidi } from '../utils/midiParser';
import { useMidiStore } from '../stores/midiStore';

/*
PURPOSE:
A custom React Hook that bridges the UI components with the MIDI parsing utility and the global Zustand store.

WHY IT EXISTS:
Components shouldn't be bogged down with the logic of orchestrating parsing utilities and updating multiple store values. This custom hook encapsulates that workflow into a single, easy-to-use function.

REACT CONCEPT:
Custom Hook. It allows reusing stateful logic (accessing Zustand) across multiple components (e.g., the Landing Page upload button, the Editor upload button, drag-and-drop zones).

VIVA QUESTION:
Why is `useMidiParser` a Custom Hook instead of a regular helper function?

VIVA ANSWER:
Because it needs to access other React Hooks (in this case, `useMidiStore` which is a hook generated by Zustand). Regular JavaScript functions cannot call React Hooks. By making it a Custom Hook, it can hook into the React lifecycle and state systems.
*/
export function useMidiParser() {
  /*
  PURPOSE:
  Extracts only the setter functions from the global store.
  
  PERFORMANCE NOTE:
  Because it only selects `setMidiData` and `setUploadedFile` (which are static references in Zustand), this hook will NOT cause the component that uses it to re-render when the actual `midiData` changes.
  */
  const { setMidiData, setUploadedFile } = useMidiStore();

  /*
  PURPOSE:
  The actual function that orchestrates the parsing flow.
  
  INPUT:
  `file`: The File object from an HTML input or drag-and-drop event.
  
  OUTPUT:
  Returns the parsed JSON data if successful, or `null` if it fails. Also updates the global store as a side effect.
  
  REACT CONCEPT:
  `useCallback` caches the function definition between renders.
  
  VIVA QUESTION:
  Why did you wrap the `parse` function in `useCallback`?
  
  VIVA ANSWER:
  If a component passes this `parse` function down to child components as a prop, recreating the function on every render would cause unnecessary re-renders of those children. `useCallback` ensures the function reference remains stable unless its dependencies (`setMidiData`, `setUploadedFile`) change.
  */
  const parse = useCallback(async (file) => {
    if (!file) return null;
    try {
      // 1. Optimistically set the filename in the UI
      setUploadedFile(file.name || 'Untitled.mid');
      
      // 2. Await the web worker parsing
      const parsed = await parseMidi(file);
      
      // 3. Update the global state with the parsed data
      setMidiData(parsed);
      
      return parsed;
    } catch (err) {
      console.error('[useMidiParser] Failed to parse MIDI file:', err);
      return null;
    }
  }, [setMidiData, setUploadedFile]);

  return { parse };
}

/*
========================================
FILE SUMMARY
========================================

Purpose:
A custom React hook (`useMidiParser`) that orchestrates the flow of receiving a file, calling the Web Worker utility (`parseMidi`), and updating the global Zustand store (`useMidiStore`) with the result.

Data Flow:
Component `parse(file)` -> Hook calls `parseMidi(file)` -> Waits for Worker -> Hook calls `setMidiData(parsed)` -> Store updates.

Important Variables:
- `parse`: The memoized asynchronous function returned by the hook.

Important Functions:
- `useMidiParser`: The hook itself.

React Concepts Used:
- Custom Hooks (encapsulating logic that uses other hooks).
- `useCallback` (memoizing functions to prevent unnecessary re-renders).

JavaScript Concepts Used:
- Async/await inside a React Hook.
- Error handling with try/catch.

Performance Considerations:
- **`useCallback`:** Prevents referential instability of the returned `parse` function.
- **Zustand Selective Binding:** By only pulling out the setters (`setMidiData`, `setUploadedFile`), components that use this hook purely to *upload* a file won't unnecessarily re-render every time the playback changes the global `midiData`.

Most Likely Viva Questions:
1. What is the difference between a custom hook and a utility function?
2. Why is `useCallback` important here?
3. What happens if the `parseMidi` function throws an error?

Tricky Follow-Up Questions:
1. Can a regular JS function call `useMidiStore()`? (Answer: Yes, Zustand actually allows fetching store state outside of React components using `useMidiStore.getState()`, but using it as a hook is standard within components).
2. What happens if the user uploads a corrupted file?

Expected Answers:
1. A custom hook can call other React hooks (like `useState`, `useEffect`, or store hooks). A standard utility function cannot.
2. It memoizes the `parse` function, keeping its memory address the same across re-renders. This prevents child components that receive `parse` as a prop from needlessly re-rendering.
3. The `try/catch` block catches the rejected Promise, logs an error to the console, and safely returns `null` without crashing the application.
4. *Follow-up 2:* The Web Worker's `midi.worker.js` try/catch block will fail, send `{success: false}` back, causing `parseMidi` to reject the Promise, which is then caught by this hook's catch block.
*/
